# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm  # <--- Ajoutez cette ligne (obligatoire)

    mappings:
        plant_images:
            uri_prefix: /uploads/plants
            upload_destination: '%kernel.project_dir%/public/uploads/plants'
            namer: App\Naming\PlantNamer # Ou Vich\UploaderBundle\Naming\SmartUniqueNamer
